import os

# Define the curriculum hierarchy for Operating Systems
curriculum = {
    "introduction-to-os": [
        "what-is-operating-system",
        "goals-of-operating-system",
        "functions-of-os",
        "types-of-operating-systems",
        "batch-operating-system",
        "multiprogramming-os",
        "multitasking-os",
        "multiprocessing-os",
        "distributed-os",
        "real-time-operating-system",
        "embedded-operating-system",
        "network-operating-system",
        "mobile-operating-system",
        "os-services",
        "user-mode-vs-kernel-mode",
        "system-calls-introduction",
        "booting-process",
        "bios-vs-uefi",
        "operating-system-architecture"
    ],
    "process-management": [
        "process-concept",
        "process-vs-program",
        "process-states",
        "process-control-block",
        "process-life-cycle",
        "context-switching",
        "process-scheduling",
        "scheduling-criteria",
        "scheduling-queues",
        "cpu-scheduler",
        "long-term-scheduler",
        "short-term-scheduler",
        "medium-term-scheduler",
        "fcfs-scheduling",
        "sjf-scheduling",
        "srtf-scheduling",
        "priority-scheduling",
        "round-robin-scheduling",
        "multilevel-queue-scheduling",
        "multilevel-feedback-queue",
        "starvation-and-aging",
        "thread-concept",
        "multithreading",
        "user-level-threads",
        "kernel-level-threads",
        "thread-vs-process",
        "thread-pool",
        "multicore-programming",
        "interprocess-communication",
        "shared-memory",
        "message-passing",
        "pipes-and-fifos",
        "sockets-introduction",
        "rpc-mechanism",
        "signals-in-os"
    ],
    "synchronization": [
        "process-synchronization",
        "race-condition",
        "critical-section-problem",
        "peterson-solution",
        "synchronization-hardware",
        "mutex-lock",
        "semaphore",
        "binary-semaphore",
        "counting-semaphore",
        "monitors",
        "condition-variables",
        "spinlock",
        "busy-waiting",
        "producer-consumer-problem",
        "readers-writers-problem",
        "dining-philosophers-problem",
        "sleeping-barber-problem",
        "deadlock-introduction",
        "deadlock-conditions",
        "resource-allocation-graph",
        "deadlock-prevention",
        "deadlock-avoidance",
        "bankers-algorithm",
        "deadlock-detection",
        "deadlock-recovery",
        "livestock-vs-starvation"
    ],
    "memory-management": [
        "memory-management-introduction",
        "address-binding",
        "logical-vs-physical-address",
        "dynamic-loading",
        "dynamic-linking",
        "swapping",
        "contiguous-memory-allocation",
        "fragmentation",
        "internal-fragmentation",
        "external-fragmentation",
        "compaction",
        "paging",
        "segmentation",
        "paging-vs-segmentation",
        "page-table",
        "multilevel-paging",
        "inverted-page-table",
        "translation-lookaside-buffer",
        "virtual-memory",
        "demand-paging",
        "page-fault",
        "copy-on-write",
        "page-replacement-introduction",
        "fifo-page-replacement",
        "lru-page-replacement",
        "optimal-page-replacement",
        "second-chance-algorithm",
        "thrashing",
        "working-set-model",
        "memory-allocation-algorithms",
        "first-fit-allocation",
        "best-fit-allocation",
        "worst-fit-allocation",
        "buddy-system"
    ],
    "file-systems": [
        "file-system-introduction",
        "file-concept",
        "file-attributes",
        "file-operations",
        "file-access-methods",
        "directory-structure",
        "single-level-directory",
        "two-level-directory",
        "tree-structured-directory",
        "acyclic-graph-directory",
        "file-allocation-methods",
        "contiguous-allocation",
        "linked-allocation",
        "indexed-allocation",
        "free-space-management",
        "inode-structure",
        "file-protection",
        "access-control",
        "file-sharing",
        "journaling-file-system",
        "virtual-file-system",
        "ntfs",
        "fat-file-system",
        "ext4-file-system",
        "disk-structure",
        "disk-scheduling",
        "fcfs-disk-scheduling",
        "sstf-disk-scheduling",
        "scan-disk-scheduling",
        "cscan-disk-scheduling",
        "look-disk-scheduling",
        "clook-disk-scheduling",
        "raid-levels",
        "disk-management"
    ],
    "security-and-protection": [
        "os-security-introduction",
        "authentication",
        "authorization",
        "access-matrix",
        "capability-based-security",
        "encryption-basics",
        "malware-types",
        "viruses-and-worms",
        "trojan-horse",
        "buffer-overflow",
        "privilege-escalation",
        "secure-kernel-design",
        "firewall-basics",
        "intrusion-detection-system",
        "secure-boot",
        "operating-system-hardening"
    ],
    "linux-and-unix": [
        "introduction-to-linux",
        "linux-architecture",
        "unix-vs-linux",
        "linux-shell",
        "bash-basics",
        "linux-file-system",
        "linux-permissions",
        "chmod-command",
        "chown-command",
        "grep-command",
        "awk-command",
        "sed-command",
        "process-management-linux",
        "ps-command",
        "top-command",
        "kill-command",
        "shell-scripting",
        "cron-jobs",
        "package-management",
        "systemd-introduction",
        "linux-networking-tools",
        "ssh-and-remote-access"
    ],
    "virtualization-and-cloud": [
        "virtualization-introduction",
        "hypervisor",
        "type1-vs-type2-hypervisor",
        "virtual-machines",
        "containerization",
        "docker-basics",
        "kubernetes-introduction",
        "cloud-computing-basics",
        "iaas-paas-saas",
        "serverless-computing",
        "resource-isolation"
    ],
    "case-studies": [
        "windows-architecture",
        "linux-kernel-overview",
        "macos-architecture",
        "android-operating-system",
        "ios-operating-system",
        "monolithic-kernel",
        "microkernel",
        "hybrid-kernel",
        "exokernel",
        "unikernel"
    ],
    "advanced-operating-systems": [
        "distributed-systems-basics",
        "distributed-file-system",
        "distributed-shared-memory",
        "clock-synchronization",
        "logical-clocks",
        "vector-clocks",
        "consensus-algorithms",
        "raft-algorithm",
        "paxos-algorithm",
        "load-balancing",
        "fault-tolerance",
        "checkpointing",
        "real-time-scheduling",
        "embedded-os-design",
        "gpu-scheduling",
        "numa-architecture",
        "parallel-processing",
        "green-computing-os",
        "energy-efficient-scheduling",
        "research-topics-operating-systems"
    ]
}

base_dir = os.path.join("content", "operating-system")

for topic, lessons in curriculum.items():
    topic_path = os.path.join(base_dir, topic)
    os.makedirs(topic_path, exist_ok=True)
    for lesson in lessons:
        file_path = os.path.join(topic_path, f"{lesson}.tsx")
        if not os.path.exists(file_path):
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(f"export default function {lesson.replace('-', '_').title().replace(' ', '')}() {{\n  return <div>{lesson.replace('-', ' ').title()}</div>;\n}}\n")
print("Operating System curriculum tree generated.")
